//tornjak
export const GLOBAL_MESSEGE = 'GLOBAL_MESSEGE';

//servers
export const GLOBAL_SERVER_SELECTED = 'GLOBAL_SERVER_SELECTED';
export const GLOBAL_SERVER_INFO = 'GLOBAL_SERVER_INFO';
export const GLOBAL_TORNJAK_SERVER_INFO = 'GLOBAL_TORNJAK_SERVER_INFO';
export const GLOBAL_SERVERS_LIST = 'GLOBAL_SERVERS_LIST';
export const GLOBAL_SELECTOR_INFO = 'GLOBAL_SELECTOR_INFO';

//entries
export const GLOBAL_ENTRIES_LIST = 'GLOBAL_ENTRIES_LIST';
//agents
export const GLOBAL_AGENTS_LIST = 'GLOBAL_AGENTS_LIST';

