version: "3.8"
services:
  tornjak-frontend:
    build:
      context: ./
      dockerfile: Dockerfile.frontend-container
    container_name: tornjak-frontend
    restart: always
    ports:
      - "3000:8080"
    environment:
      - "PORT_FE=8080"
      - "REACT_APP_API_SERVER_URI=http://localhost:10000"
    #   - "REACT_APP_AUTH_SERVER_URI=http://localhost:8080"
      - "REACT_APP_SPIRE_HEALTH_CHECK=false"
    #   - "REACT_APP_SPIRE_HEALTH_CHECK_TIME=120"