FROM alpine
RUN mkdir -p /opt/spire

WORKDIR /opt/spire
ENTRYPOINT ["/opt/spire/run_backend.sh"]

COPY sample-keys sample-keys
# Add init
COPY run_backend.sh run_backend.sh
COPY bin/tornjak-backend tornjak-backend

# add a version link to the image description
ARG version
LABEL org.opencontainers.image.description "https://github.com/spiffe/tornjak/releases/tag/$version"