
FROM node:19-alpine

WORKDIR /usr/src/app

COPY tornjak-frontend .

RUN npm install --omit=dev

RUN npm prune --production

# set env variables
ENV REACT_APP_API_SERVER_URI $REACT_APP_API_SERVER_URI
ENV REACT_APP_AUTH_SERVER_URI $REACT_APP_AUTH_SERVER_URI
ENV NODE_OPTIONS $NODE_OPTIONS
ARG NODE_OPTIONS=--openssl-legacy-provider
EXPOSE 3000

CMD ["npm", "start"]