FROM ghcr.io/spiffe/spire-server:{version}

# Add init
ENTRYPOINT ["/opt/spire/run_server.sh"]
RUN apk add curl
COPY bin/tornjak-backend tornjak-backend
COPY sample-keys sample-keys
COPY run_server.sh run_server.sh
