FROM gcr.io/spiffe-io/spire-server:{version}
RUN apk add curl
COPY bin/tornjak-agent tornjak-agent
COPY ui-agent ui-agent
COPY sample-keys sample-keys


# Add init
COPY run_server.sh run_server.sh
ENTRYPOINT ["/opt/spire/run_server.sh"]
