FROM alpine:latest

WORKDIR /
#COPY ui-manager ui-manager

# Add init
ENTRYPOINT ["/tornjak-manager"]

RUN apk add curl

# add a version link to the image description
ARG version
LABEL org.opencontainers.image.description "https://github.com/spiffe/tornjak/releases/tag/$version"

COPY bin/tornjak-manager tornjak-manager