openapi: 3.1.0
info:
  title: Tornjak
  description: |
    This API allows management of SPIRE server via the Tornjak server,
    comprised of SPIRE server API calls and Tornjak-specific API calls.
  version: 1.3.0
paths:
  /api/v1/spire/healthcheck:
    get:
      summary: Query SPIRE Healthcheck status
      description: Retrieves SPIRE healthcheck status. SPIRE currently uses Google grpc_health_v1 package
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    minimum: 0
                    maximum: 3
                    description: |
                      Possible values for SPIRE server healthcheck
                      `0` means UNKNOWN
                      `1` means SERVING
                      `2` means NOT_SERVING
                      `3` means SERVICE UNKNOWN
  /api/v1/spire/serverinfo:
    get:
      summary: Get general SPIRE server information, as defined in SPIRE api-sdk
      description: Retrieves general SPIRE server information as defined in SPIRE api-sdk
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: object
                properties:
                  svid_chain:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          $ref: '#/components/schemas/spiffe_id'
                        expires_at:
                          type: integer
                        subject:
                          type: string
                  uptime:
                    type: integer
                    minimum: 0
                    description: |
                      Represents the number of seconds a SPIRE server has been running
                  federated_bundles_count:
                    type: integer
                    minimum: 0 #TODO
                    description: |
                      Represents the number fo federated bundles stored in SPIRE server
  /api/v1/spire/agents:
    get:
      summary: Calls SPIRE server `spire-server agent list` command
      description: Display attested nodes
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: object
                properties:
                  agents:
                    type: array
                    items:
                      $ref: '#/components/schemas/agent'
    delete:
      summary: Calls SPIRE server `spire-server agent evict` command
      description: Evict attested node given spiffeID so node is not able to re-attest
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/spiffe_id'
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: string
  /api/v1/spire/agents/ban:
    post:
      summary: Calls SPIRE server `spire-server agent ban` command
      description: Ban attested node given spiffeID so node is not able to re-attest
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/spiffe_id'
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: string
  /api/v1/spire/agents/jointoken:
    post:
      summary: Calls SPIRE server `spire-server token generate`
      description: Generates one node join token and creates a registration entry for it.
      requestBody:
        #required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                path:
                  type: string
                token:
                  type: integer
                trust_domain:
                  type: string
                ttl:
                  type: integer
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: object
                properties:
                  value:
                    type: integer
                  expires_at:
                    type: integer
  /api/v1/spire/entries:
    get:
      summary: Calls SPIRE server `spire-server entry show`
      description: Displays configured registration entries
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/entry'
    post:
      summary: Calls SPIRE server `spire-server entry create`
      description: Create registration entries
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/entry'
                - type: object
                  properties:
                    admin:
                      type: string
                    dns_names:
                      type: string
                    downstream:
                      type: string
                    expires_at:
                      type: string
                    federates_with:
                      type: array
                      items:
                        $ref: '#/components/schemas/TODO'
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    $ref: '#/components/schemas/entry'
    delete:
      summary: Calls SPIRE server `spire-server entry delete`
      description: Deletes a specified registration entry
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                ids:
                  type: array
                  items:
                    type: string
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: object
                properties:
                  Results:
                    type: array
                    items:
                      type: object
                      properties:
                        status:
                          type: object
                          properties:
                            messege:
                              type: string
                        id:
                          type: string


components:
  schemas:
    TODO:
      type: string

    spiffe_id:
      type: object
      properties:
        path:
          type: string
        trust_domain:
          type: string

    selector:
      type: object
      properties:
        type:
          type: string
        value:
          type: string

    entry:
      type: object
      properties:
        id:
          type: string
        spiffe_id:
          $ref: '#/components/schemas/spiffe_id'
        parent_id:
          $ref: '#/components/schemas/spiffe_id'
        selectors:
          type: array
          items:
            $ref: '#/components/schemas/selector'


    agent:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/spiffe_id'
        attestation_type:
          type: string
        x509svid_serial_number:
          type: integer
        x509svid_expires_at:
          type: integer
        selectors:
          type: array
          items:
            $ref: '#/components/schemas/selector'

