apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spire-server
  namespace: spire
  labels:
    app: spire-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spire-server
  serviceName: spire-server
  template:
    metadata:
      namespace: spire
      labels:
        app: spire-server
    spec:
      serviceAccountName: spire-server
      containers:
        - name: spire-server
          image: ghcr.io/spiffe/spire-server:1.4.4
          args:
            - -config
            - /run/spire/config/server.conf
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: spire-config
              mountPath: /run/spire/config
              readOnly: true
            - name: spire-data
              mountPath: /run/spire/data
              readOnly: false
            - name: socket                        
              mountPath: /tmp/spire-server/private
          livenessProbe:
            httpGet:
              path: /live
              port: 8080
            failureThreshold: 2
            initialDelaySeconds: 15
            periodSeconds: 60
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
        - name: tornjak-backend
          image: docker.io/maiariyer/tornjak-backend:v1.3.0
          args:
            - --spire-config
            - /run/spire/config/server.conf
            - --tornjak-config
            - /run/spire/tornjak-config/server.conf
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: spire-config
              mountPath: /run/spire/config
              readOnly: true
            - name: tornjak-config
              mountPath: /run/spire/tornjak-config
              readOnly: true
            - name: spire-data
              mountPath: /run/spire/data
              readOnly: false
            - name: socket
              mountPath: /tmp/spire-server/private
            - name: tls-volume              # 👈 TLS SECRET VOLUME MOUNT
              mountPath: /opt/spire/server  # 👈 TLS SECRET VOLUME MOUNT
            - name: user-cas                # 👈 mTLS CA SECRET VOLUME MOUNT
              mountPath: /opt/spire/users   # 👈 mTLS CA SECRET VOLUME MOUNT
      volumes:
        - name: spire-config
          configMap:
            name: spire-server
        - name: tornjak-config  
          configMap:            
            name: tornjak-agent
        - name: socket        
          emptyDir: {}    
        - name: tls-volume                  # 👈 TLS SECRET VOLUME
          secret:                           # 👈 TLS SECRET VOLUME
            secretName: tornjak-server-tls  # 👈 TLS SECRET VOLUME
        - name: user-cas                    # 👈 mTLS CA SECRET VOLUME
          secret:                           # 👈 mTLS CA SECRET VOLUME
            secretName: tornjak-user-certs  # 👈 mTLS CA SECRET VOLUME
  volumeClaimTemplates:
    - metadata:
        name: spire-data
        namespace: spire
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
