name: Markdown Linter
on: [pull_request, push]
permissions:
  contents: read
jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: ljharb/actions/node/install@main
        name: 'nvm install lts/* && npm install'
      - run: npm run lint