name: Markdown Linter
on: [pull_request, push]
permissions:
  contents: read
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DavidAnson/markdownlint-cli2-action@v17
      continue-on-error: true
      with:
        fix: true
        config: '../.markdownlint.yml'
        globs: |
          docs/*.md
          !examples/*.md